version: "3.8"

services:


  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db
    networks:
      - mynetwork
  postgres_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: